// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxKmm-NzmwWiycQZfWDf2ZP7vNKp_Js7s',
    appId: '1:176154665685:web:572ab43cad0b1260d6385c',
    messagingSenderId: '176154665685',
    projectId: 'push-notifications-1500b',
    authDomain: 'push-notifications-1500b.firebaseapp.com',
    storageBucket: 'push-notifications-1500b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6nOit6CjA-UjMxAWT7luvaVwtUPrae5k',
    appId: '1:176154665685:android:cc57711629b10e1bd6385c',
    messagingSenderId: '176154665685',
    projectId: 'push-notifications-1500b',
    storageBucket: 'push-notifications-1500b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1CBvlSts97gZVKVDNsWe9LjfK7iRzOko',
    appId: '1:176154665685:ios:03393a404c02f0c5d6385c',
    messagingSenderId: '176154665685',
    projectId: 'push-notifications-1500b',
    storageBucket: 'push-notifications-1500b.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1CBvlSts97gZVKVDNsWe9LjfK7iRzOko',
    appId: '1:176154665685:ios:bbe9bddc65f49278d6385c',
    messagingSenderId: '176154665685',
    projectId: 'push-notifications-1500b',
    storageBucket: 'push-notifications-1500b.appspot.com',
    iosBundleId: 'com.example.pushNotification.RunnerTests',
  );
}
